<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="ModelContextProtocol.Core" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Mcp.Protocol.Handwritten\Mcp.Protocol.Handwritten.csproj" />
    <ProjectReference Include="..\..\src\DotNetMcpServer.Server\DotNetMcpServer.Server.csproj" />
    <ProjectReference Include="..\..\src\DotNetMcpServer.Agent\DotNetMcpServer.Agent.csproj" />
  </ItemGroup>

</Project>
